global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'udehnih-report'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
